version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/python:3.6-jessie-node-browsers

filter_only_master: &filter_only_master
  filters:
    branches:
      only: master

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package
          keys:
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          name: Save npm package
          key: node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  build_for_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run generate:test
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:unit
      - run: npm run test:e2e
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist

  build_for_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run generate:production
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://aws-rough.cc --exact-timestamps --delete --exclude "*.html" --cache-control max-age=31536000
      - run: aws s3 sync ./dist/ s3://aws-rough.cc --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  version: 2
  test-deploy:
    jobs:
      - install
      - build_for_test:
          requires:
            - install
      - test:
          requires:
            - build_for_test
      - build_for_production:
          requires:
            - test
      - deploy:
          <<: *filter_only_master
          requires:
            - build_for_production